[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
  GATSBY_RECAPTCHA_V3_SITE_KEY="6Lfjg90qAAAAAA4UOoAGP8KTCeJVq8GmvKqJEVni"
